
import React, { useState } from 'react';
import './styles/meeting-notes.scss';

function App() {
  const [file, setFile] = useState(null);
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);

  // Placeholder summarization logic
  const handleSummarize = () => {
    if (!file) return;
    setLoading(true);
    setTimeout(() => {
      setSummary('This is a sample summary of your meeting notes. In the real app, this would be generated by an AI model based on your uploaded file.');
      setLoading(false);
    }, 1500);
  };

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setSummary('');
  };

  const handleShare = (platform) => {
    alert(`Pretend sharing summary to ${platform}!`);
  };

  return (
    <div className="app-container">
      <div className="header">
        <h1>AI Meeting Notes Summarizer</h1>
        <p>Upload your meeting notes and get a concise summary to share with your team.</p>
      </div>

      <div className="upload-section">
        <label className="upload-label" htmlFor="meeting-notes-upload">Upload Meeting Notes (.txt, .docx, .pdf)</label>
        <input id="meeting-notes-upload" type="file" accept=".txt,.docx,.pdf" onChange={handleFileChange} />
        <button className="summarize-btn" onClick={handleSummarize} disabled={!file || loading}>
          {loading ? 'Summarizing...' : 'Summarize'}
        </button>
      </div>

      {summary && (
        <div className="summary-section">
          <div className="summary-title">Summary</div>
          <div className="summary-content">{summary}</div>
          <div className="share-section">
            <button className="share-btn" onClick={() => handleShare('Email')}>Share via Email</button>
            <button className="share-btn" onClick={() => handleShare('Slack')}>Share to Slack</button>
            <button className="share-btn" onClick={() => handleShare('Copy Link')}>Copy Link</button>
          </div>
        </div>
      )}
    </div>
  );
}



export default App
